name: Build NW.js PC Version

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-windows:
    runs-on: windows-2025

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 26.1.0
        uses: actions/setup-node@v4
        with:
          node-version: '26.1.0'

      - name: Install nw-builder
        run: npm install nw-builder@latest --save-dev

      - name: Build NW.js app
        # Вот здесь мы добавили --glob=false, чтобы исправить ошибку с package.json
        run: npx nwbuild --mode=build --platform=win --arch=x64 --version=0.111.3 --flavor=normal --glob=false --app.name="TinyBunny" --outDir=out ./

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TinyBunny-Windows-Build
          path: out/
